[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
java = "17"
minecraft = "1.20.1"
fabric_loader = "0.16.10"

# Mappings
yarn_mappings = "1.20.1+build.10"

yumi_commons = "1.0.0-alpha.1"

fabric_api = "0.92.3+1.20.1"
modmenu = "4.0.6"

# For Gradle And MModding Config
quilt_parsers = "0.3.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

# Mappings
yarn_mappings = { module = "net.fabricmc:yarn", version.ref = "yarn_mappings" }

# Yumi Commons
yumi_commons = { module = "dev.yumi.commons:yumi-commons", version.ref = "yumi_commons" }
yumi_commons_core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi_commons" }
yumi_commons_collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi_commons" }
yumi_commons_event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi_commons" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# For Gradle And MModding Config
quilt_parsers_json = { module = "org.quiltmc.parsers:json", version.ref = "quilt_parsers" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.10-SNAPSHOT" }
mmodding_gradle = { id = "com.mmodding.gradle", version = "0.0.15" }
