[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.2"
quilt_mappings = "1.19.2+build.21"
quilt_loader = "0.17.6"

quilted_fabric_api = "4.0.0-beta.18+0.64.0-1.19.2"
modmenu = "4.0.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

# If you have multiple similar dependencies, you can declare a dependency bundle and reference it on the build script with "libs.bundles.example".
# [bundles]
# example = ["example-a", "example-b", "example-c"]

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }
